/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.31
</auto-generated>
------------------------------------------------------------------------------ */

using SFDevApril2023.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SFDevApril2023.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "LinoWidget_MVC", Title = "LinoWidget", SectionName = "CustomWidgets")]
	public class LinoWidgetController : Controller, IPersonalizable
	{
		// GET: LinoWidget
		public ActionResult Index()
		{
			var model = new LinoWidgetModel();
			model.Message = this.Message;
			return View(model);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Message { get; set; }
	}
}