/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.31
</auto-generated>
------------------------------------------------------------------------------ */

using Progress.Sitefinity.Renderer.Designers.Attributes;
using Progress.Sitefinity.Renderer.Entities.Content;
using SFDevApril2023.Mvc.Models;
using System;
using System.ComponentModel;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SFDevApril2023.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "Nick", Title = "Nick", SectionName = "SFDevApril2023")]
	public class NickController : Controller, IPersonalizable
	{
		// GET: Nick
		public ActionResult Index()
		{
			var model = new NickModel();
			model.Message = this.Message;
            model.Number = this.Number;
            model.MyDate = this.MyDate;
            model.Flag = this.Flag;
            model.Enum = this.Enum;
			return View("Index", model);
		}

        public ActionResult Arun()
        {

            return View("Arun");
        }
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

        public string Message { get; set; }
        [Category("Lino")]
        public bool Flag { get; set; }
        public Enumeration Enum { get; set; }
        [Browsable(false)]
        public int Number { get; set; }
        public DateTime MyDate { get; set; }

        [Content(Type = KnownContentTypes.Images)]
        public MixedContentContext Images { get; set; }

        [Content(Type = KnownContentTypes.Pages)]
        public MixedContentContext Pages { get; set; }

        [Content(Type = KnownContentTypes.News)]
        public MixedContentContext News { get; set; }
    }
}